// Every static string the interface shows. Views may show a string from here or a string from the read. Nothing else.
// Templates use {name} slots; fill() puts read values into them. The no-opinions test knows about both.
export const copy = {
  brand: 'Sepiola',
  rink: {
    title: 'My rink',
    subEmpty: 'Cue a roster to load the board',
    subBefore: 'Lineup before the ice is read',
    subAfter: 'Ice read for the next {days} days',
    subRead: 'Ice read',
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    weekStarting: 'Week starting',
  },
  legend: {
    fresh: 'fresh ice: the schedule is on his side',
    chewed: 'chewed up: light week, or a back-to-back',
    badges: 'Badges:',
    flag: 'flag',
    stream: 'stream candidate',
  },
  strips: {
    bench: 'Bench',
    ir: 'Injured reserve',
    benchEmpty: 'Nobody on the bench.',
    irEmpty: 'Nobody in the box.',
  },
  glyph: { warn: '!', stream: '↗', b2b: 'b2b', game: 'G' },
  replay: {
    title: 'Replay',
    sub: 'run it back',
    pts: '{pts} projected pts',
    soft: 'soft night',
    hard: 'hard night',
    empty: 'Run it back on a skater and his week shows up here.',
  },
  panel: {
    sub: 'the calls',
    help: {
      start: 'Start: play him this week.',
      sit: 'Sit: leave him on your bench this week.',
      ir: 'IR: injured reserve, not playing.',
      stream: 'Stream: worth picking up for this week, then letting go.',
    },
    source: 'Where these numbers come from',
    empty: 'Nothing read yet. Run read_ice, or let your agent call it.',
    start: 'Start', sit: 'Sit', ir: 'IR', stream: 'Stream',
    why: 'why',
  },
  hand: {
    sub: 'who skates more',
    empty: 'Run the ice to see the edge.',
    you: 'You', opp: 'Opp',
    help: 'Games in hand: how many games your team plays this week versus your opponent. More games usually means more points.',
    expand: 'Both rosters',
    collapse: 'Totals only',
    colGames: 'games',
    colPts: 'pts',
  },
  siteTools: {
    none: 'Site tools: not available in this browser',
    on: 'Site tools: {n} registered',
    fixture: 'fixtures',
    live: 'live · {url}',
  },
  demo: {
    intro: 'Watch the pen. These are the same moves an agent makes.',
    circle: 'Circle him. The spotlight pins the analyst\'s reason above the skater.',
    replay: 'Run it back. His week replays as tiles, then the analyst\'s line drops.',
    split: 'Split screen. Two weeks side by side; the call is the analyst\'s, not the page\'s.',
    panel: 'Cut to the panel. Every call and every sentence here came from the analyst.',
    done: 'Your turn. Click any skater, or paste your own lineup.',
    skip: 'Skip',
    close: 'Explore',
  },
  skaterMenu: {
    spotlight: 'Spotlight',
    replay: 'Run it back',
    compare: 'Compare with…',
  },
  pick: {
    banner: 'Compare {name} with… click another skater.',
    cancel: 'Cancel',
  },
  history: {
    games: '{you} vs {opp} games',
    gamesSolo: '{you} games',
    restore: 'Restore',
    again: 'Run again',
    raw: 'command and result',
    restored: 'restored · {label}',
    gone: 'That read is no longer kept. Run it again.',
  },
  console: {
    paste: 'Paste a lineup',
    pasteGo: 'Cue it',
    pasted: 'cue_roster (pasted lineup)',
    ready: 'Talkback ready. One move per line.',
    hint: 'The seven moves',
    placeholder: 'read_ice',
    run: 'Run',
  },
  paste: {
    formats: 'What "one player per line" means',
    lead: 'Any of these, mixed freely. Names are matched against the NHL\'s player index; a surname alone works when it is unique.',
    examples: [
      ['Name and position', 'Connor McDavid C'],
      ['Bench or injured reserve first', 'BN Ryan Strome C'],
      ['Last name, first name', 'Matthews, Auston'],
      ['A ranked list', '1. Nathan MacKinnon COL - C'],
      ['A row copied from a fantasy site', 'D    Cale Makar    COL - D    Q'],
      ['Just a surname', 'Nylander'],
    ],
    opponent: 'Opponent\'s lineup (optional)',
    opponentHint: 'Paste the other side too and games in hand gets its second bar and the analyst\'s edge.',
    useSample: 'Use the sample lineup',
    sample: 'Connor McDavid C\nMatvei Gridin LW\nMatt Coronato RW\nMorgan Frost C\nConnor Zary LW\nJoel Farabee RW\nCale Makar D\nRasmus Andersson D\nMacKenzie Weegar D\nKevin Bahl D\nDustin Wolf G\nBN Ryan Strome C\nBN Mikael Backlund C\nIR Jonathan Huberdeau LW',
  },
  signal: {
    title: 'Two sides of one screen',
    line: 'The analyst decides. The pen draws. The screen has no opinions.',
    pen: {
      heading: 'The pen · WebMCP',
      what: 'Tools this page registers with the browser, so an agent running in it can make the seven moves.',
      pill: 'WebMCP',
      on: '{n} tools registered with the browser\'s modelContext',
      off: 'Not available in this browser. Chrome with WebMCP enabled (chrome://flags, or --enable-features=WebMCP), or the Codex desktop browser, registers them.',
      pillOn: '{n} tools',
      pillOff: 'no agent here',
    },
    analyst: {
      heading: 'The analyst · CHIRP',
      what: 'The server that reads the ice: an MCP server with an HTTP face. It computes every number and writes every line; the page only draws them.',
      pill: 'Analyst',
      live: 'live',
      fixtures: 'fixtures',
      fixturesLine: 'Built-in reads. No network, no analyst.',
      checking: 'checking…',
      health: '{analyst} · season {season} · answered in {ms} ms',
      mcp: 'Also an MCP server: {tools} tools at {endpoint}, stateless — pass your lineup with each call.',
      down: 'Did not answer.',
      hint: 'Point the page elsewhere with ?analyst=<url>, or at nothing with ?analyst=fixtures.',
    },
    more: 'How it works',
    connect: 'Connect your agent',
  },
  windows: { rink: 'Rink', panel: 'Panel', hand: 'Games in hand', replay: 'Replay', console: 'Console', welcome: 'Start here', about: 'About' },
  menu: {
    windows: 'Windows',
    start: 'Start here',
    sample: 'Load a sample week',
    about: 'About Sepiola',
    quickStart: 'Quick start',
    github: 'GitHub',
    privacy: 'Privacy',
    terms: 'Terms',
    disclaimer: 'Disclaimer',
  },
  welcome: {
    title: 'Sepiola',
    sub: 'a screen for an analyst\'s read',
    lead: 'An AI analyst reads your fantasy-hockey week — who plays, who sits on a back-to-back, who to stream — and instead of writing you a paragraph, it draws the read here. The page draws; the analyst decides.',
    hockeyDoor: 'I play fantasy hockey',
    buildDoor: 'I build with agents',
    connect: 'Connect your agent',
    connectHint: 'Chrome, Codex, or any MCP client: three ways in.',
    sample: 'Watch a sample week',
    sampleHint: 'Fifteen seconds: the moves an agent makes, played on a sample roster.',
    paste: 'Paste your lineup',
    pasteHint: 'Any platform, one player per line. Names resolve against the NHL.',
    learn: 'How it works',
    learnHint: 'The pattern, the seven moves, the paper.',
    newHere: 'New to fantasy hockey, or to AI agents? The words, explained.',
  },
  about: {
    title: 'About Sepiola',
    sub: 'what this is, how to use it, and the fine print',
    sections: {
      about: {
        heading: 'About',
        paras: [
          'Sepiola is a telestrator: a page that draws an analyst\'s read onto a persistent screen. The analyst is CHIRP, an open-source fantasy-hockey intelligence server. Any agent that speaks WebMCP is the pen. This page is the screen, and the screen has no opinions: every number and every sentence on it comes from the analyst\'s read.',
          'The name is the bobtail squid. A cuttlefish\'s skin is a display of millions of pigment cells driven directly by its brain; the skin decides nothing. And the passing cloud, a dark wave that travels across the body to hold prey still, is a spotlight done by an animal.',
          'Built by semanticintent as an open-source demonstration of the telestrator pattern. Source, contract, and decisions are on GitHub.',
        ],
      },
      quickStart: {
        heading: 'Quick start',
        steps: [
          'Watch first. Press Watch a sample week on the welcome card. For fifteen seconds the page shows you what it does on a made-up team.',
          'Bring your team. Press Paste a lineup, copy your roster from whatever fantasy site you use, paste it, and press Cue it. One player per line; the format does not matter.',
          'Read the week. The page asks the analyst about the coming week and draws the answer: the ice under each player, the calls in the panel, and who has more games.',
          'Ask why. Click any player for a menu: Spotlight shows the reason on the rink, Run it back replays his week, Compare with puts two players side by side.',
          'Pick another week. Use the arrows next to the date on the rink to move a week back or forward.',
          'Everything you do is written in the Talkback on the right. An AI agent can make exactly the same moves, and you would see each one there too.',
        ],
      },
      words: {
        heading: 'The words, in plain language',
        paras: ['Three vocabularies meet on this page: fantasy hockey, the TV broadcast it borrows from, and the technology underneath. These are only the words on this screen; linked terms open their full entry.'],
        link: { href: 'https://chirp.semanticintent.dev/glossary.html', label: 'The full ChirpIQX glossary: over 150 fantasy-hockey terms, from ADP to waiver priority' },
        defs: [
          ['Fantasy hockey', 'A game where you pick real NHL players for your own team and score points when they play well. Players only score on days their real team plays.', 'https://chirp.semanticintent.dev/glossary.html#fantasy-hockey'],
          ['Lineup', 'The players on your fantasy team this week, and where each one sits: playing, on the bench, or injured.', 'https://chirp.semanticintent.dev/glossary.html#lineup'],
          ['Start / Sit', 'Start means play him this week; sit means leave him on your bench. The analyst calls these from how many games each player has.', 'https://chirp.semanticintent.dev/glossary.html#start-sit'],
          ['Stream', 'Picking up a player for a short stretch because his team plays a lot that week, then letting him go.', 'https://chirp.semanticintent.dev/glossary.html#streaming'],
          ['Back-to-back', 'Two games on consecutive days. Tired legs, and often a backup goalie. Marked b2b on the rink.', 'https://chirp.semanticintent.dev/glossary.html#back-to-back-b2b'],
          ['Games in hand', 'How many games your whole team plays this week versus your opponent. More games usually means more points.', 'https://chirp.semanticintent.dev/glossary.html#games-in-hand'],
          ['IR', 'Injured reserve: players who are hurt and not playing.', 'https://chirp.semanticintent.dev/glossary.html#ir-injured-reserve'],
          ['Ice quality', 'The patch under each player. Fresh, glossy ice means a good week for him; chewed-up ice means a light week or a back-to-back.', 'https://chirp.semanticintent.dev/glossary.html#schedule-density'],
          ['The analyst', 'CHIRP, the program that reads the NHL schedule and statistics and makes every call. This page only draws what it says.'],
          ['The read', 'One answer from the analyst about one week: every player, every call, every sentence.', 'https://chirp.semanticintent.dev/glossary.html#the-read-read-ice'],
          ['Run it back', 'TV slang for a replay. Here it replays one player\'s week as tiles, then shows the analyst\'s verdict.'],
          ['Talkback', 'In TV, the line from the control room to the studio. Here, the box where every move is written down, and where you can type moves yourself.'],
          ['Telestrator', 'The pen TV analysts use to draw circles and arrows on a paused game. This page is one, for an AI analyst.', 'https://chirp.semanticintent.dev/glossary.html#telestrator'],
          ['AI agent', 'An AI assistant that can take actions, not just answer. Here, one that can draw on this page for you.'],
          ['MCP', 'Model Context Protocol: a standard way for an AI assistant to use outside tools. The analyst speaks it.', 'https://chirp.semanticintent.dev/glossary.html#mcp-model-context-protocol'],
          ['WebMCP', 'The same idea inside a web page: the page tells an AI in your browser which actions it offers. This page offers seven.', 'https://chirp.semanticintent.dev/glossary.html#webmcp'],
        ],
      },
      connect: {
        heading: 'Connect your agent',
        steps: [
          'Chrome: open chrome://flags, search for WebMCP, enable it, relaunch, and reload this page. The WebMCP lamp turns green and an agent in the browser can make all seven moves.',
          'Codex: open this page in the Codex desktop app\'s browser. It discovers the seven moves on its own.',
          'Any MCP client: add the analyst as a remote server. It is stateless, so pass your lineup with each call. For Claude Code:',
        ],
        code: 'claude mcp add --transport http chirp https://chirp-mcp.semanticintent.dev/mcp',
        paras: ['Any client that speaks Streamable HTTP can use https://chirp-mcp.semanticintent.dev/mcp directly. The page and the server are two faces of one analyst: the page shows, the server answers.'],
      },
      privacy: {
        heading: 'Privacy',
        paras: [
          'No accounts, no sign-in, no cookies, no analytics, no tracking scripts. The page does not store anything in your browser.',
          'When you paste a lineup, the text is sent to the analyst at chirp-mcp.semanticintent.dev so player names can be resolved against the NHL\'s public player index and a read can be computed. The analyst is stateless: it does not store your lineup, and the read is returned to your browser and kept only there, until you reload.',
          'The analyst runs on Cloudflare. Cloudflare may keep ordinary request metadata (such as IP address and timestamps) for a limited time for security, rate limiting, and operations. We do not use it to identify you.',
          'Fixture mode (add ?analyst=fixtures to the address) makes no network requests at all.',
        ],
      },
      terms: {
        heading: 'Terms',
        paras: [
          'Sepiola is provided as is, without warranty of any kind, under the MIT licence. Use it at your own risk.',
          'You are responsible for the lineup text you paste. If it comes from a fantasy platform, its terms of service govern what you may copy from it. Player names, positions, clubs, and schedules are public information published by the NHL.',
          'Sepiola is not affiliated with, endorsed by, or connected to the NHL, any of its clubs, the NHLPA, or any fantasy-sports platform. No team logos, wordmarks, or jersey designs are used; the jerseys are generic shapes in club colours.',
          'These terms may change as the project does. The current version is always the one served here and in the repository.',
        ],
      },
      disclaimer: {
        heading: 'Disclaimer',
        paras: [
          'Everything on this screen is for entertainment and information. Start, sit, and stream calls are the analyst\'s reading of the published schedule and last season\'s production; they are not predictions and they will be wrong sometimes. Make your own decisions.',
          'Schedules change. Injuries happen. The read is only as current as the NHL\'s public data at the moment it was made, and the panel says where every number came from.',
        ],
      },
      credits: {
        heading: 'Credits',
        paras: [
          'Barlow and Barlow Condensed by Jeremy Tribby, under the SIL Open Font License 1.1. Motion by GSAP. Schedule and statistics from the NHL\'s public API. The original mockup and pattern were drafted with Claude; the code was built with Claude Code.',
          'The mark is a bobtail squid drawn as a crest: flat fills, one bold line, and the passing cloud across its mantle. It is the project\'s own and carries no team\'s colours. The voxel Sepiola on the project\'s social card was generated with ChatGPT and adapted to the same palette.',
        ],
      },
    },
  },
  errors: {
    noRoster: 'Cue a roster first.',
    unknownFixture: 'No fixture called "{name}".',
    unknownSkater: 'No skater on the ice called "{id}".',
    unknownId: 'No skater in the read called "{id}".',
    sameSkater: 'Split needs two different skaters.',
    unknownWindow: 'No window called "{view}". Try rink, panel, hand, replay, or console.',
    expectedNumber: 'Expected a number for {key}. Try: {example}',
    badDays: 'look_ahead_days must be a whole number from 1 to 14. Try: {example}',
    needsRoster: 'Give cue_roster a fixture name, or a pasted lineup when an analyst is configured.',
    noAnalyst: 'No analyst is configured. Load a fixture with cue_roster <fixture>, or open the page with ?analyst=<url>.',
    analystDown: 'The analyst did not answer at {url}.',
    badRead: 'The analyst returned something the screen cannot draw: {why}.',
    unknownMove: 'Unknown move "{name}".',
  },
};

export const fill = (template, vars) => template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));

/** Every leaf string in copy, for tests. */
export function leaves(node = copy, out = []) {
  for (const v of Object.values(node)) typeof v === 'string' ? out.push(v) : leaves(v, out);
  return out;
}
